spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 157977
    url: jdbc:mysql://localhost:3306/books?useSSL=false&useUnicode=true&characterEncoding=utf-8
  jpa:
    show-sql: true
logging:
  level:
    cn.edu.ncu.bootjpademo: debug